# Generated by Django 6.0.4 on 2026-04-26 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('professor', 'Professor'), ('associate_professor', 'Associate Professor'), ('assistant_professor', 'Assistant Professor'), ('lecturer', 'Lecturer')], max_length=50)),
                ('department', models.CharField(choices=[('cs', 'Computer Science'), ('ec', 'Electronics'), ('me', 'Mechanical'), ('ce', 'Civil'), ('it', 'Information Technology')], max_length=50)),
                ('joining_date', models.DateField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('journal', 'Journal'), ('conference', 'Conference'), ('book', 'Book'), ('book_chapter', 'Book Chapter')], max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('month', models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
                ('year', models.IntegerField()),
                ('pages', models.CharField(blank=True, max_length=50)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='publications/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_name', models.CharField(blank=True, max_length=300)),
                ('issn', models.CharField(blank=True, max_length=50)),
                ('volume', models.CharField(blank=True, max_length=50)),
                ('issue', models.CharField(blank=True, max_length=50)),
                ('conference_name', models.CharField(blank=True, max_length=300)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('conference_isbn', models.CharField(blank=True, max_length=50)),
                ('book_name', models.CharField(blank=True, max_length=300)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('book_isbn', models.CharField(blank=True, max_length=50)),
                ('chapter_number', models.CharField(blank=True, max_length=50)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='core.faculty')),
            ],
        ),
    ]
