# Generated by Django 6.0.4 on 2026-05-17 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(help_text='Name of the faculty', max_length=200)),
                ('title', models.CharField(help_text='Title of the paper', max_length=500)),
                ('type', models.CharField(choices=[('journal', 'Journal'), ('conference', 'Conference'), ('book', 'Book'), ('book_chapter', 'Book Chapter')], default='journal', help_text='Publication type', max_length=50)),
                ('journal_conference', models.CharField(help_text='Name of the Journal/Conference', max_length=500)),
                ('page_no', models.CharField(blank=True, help_text='Page number', max_length=100)),
                ('vol_issue', models.CharField(blank=True, help_text='Vol.No/Issue No', max_length=100)),
                ('year', models.IntegerField(help_text='Publication year (2018-2024)')),
                ('doi', models.CharField(blank=True, help_text='DOI identifier', max_length=300)),
                ('indexed', models.CharField(choices=[('SCOPUS', 'SCOPUS'), ('WOS', 'WOS'), ('WOS-SCI', 'WOS-SCI'), ('WOS-ESCI', 'WOS-ESCI')], help_text='Indexing type', max_length=20)),
                ('quartile', models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], help_text='Journal quartile', max_length=5)),
                ('pdf_file', models.FileField(blank=True, help_text='Upload PDF file', null=True, upload_to='publications/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='core.faculty')),
            ],
            options={
                'ordering': ['-year', '-created_at'],
            },
        ),
    ]
