# Generated by Django 6.0.4 on 2026-05-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='publication_date',
            field=models.CharField(blank=True, help_text='Full Date/Month-Year', max_length=100),
        ),
    ]
